org: pmuehleip
app: reverse-dictionary-backend
service: reverse-dictionary-backend

frameworkVersion: '3'

#useDotenv: true

custom:
  wsgi:
    app: app.app
    pythonBin: python3

provider:
  name: aws
  #runtime: python3.9

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-wsgi
  - serverless-python-requirements
